config/routes.rb
Rails.application.routes.draw do
  get 'friendships/index'

  get 'friendships/create'

  get 'friendships/new'

  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'users/index'

  get 'users/create'
  get 'users/edit'
  post 'users/update'

  get 'welcome/index'

  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :messages
  resources :friendships
  post '/register' => 'users#create'
  post '/login' => 'sessions#create'
  get '/sent' => 'messages#show_sent'
  get '/show_message' => 'messages#show_message'
  get '/block' => 'friendships#block_friend'
  get '/remove_friend' => 'friendships#remove_friend'

  root 'welcome#index'

end

app/models/friend_list.rb
class FriendList < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :messages
  mount_uploader :avatar, AvatarUploader

  def status
    self.friendships.find_by_friend_id(self.id).status
  end
end

app/models/users_message.rb
class UsersMessage < ActiveRecord::Base
end

app/models/users_relationship.rb
class UsersRelationship < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :authorize_user?
  def authorize_user?
    session['user_id']? true: false
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :set_user
  def index
    @friends = @user.friends

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def create
    if Friendship.where("user_id = ? AND friend_id = ?", session[:user_id], params[:id]) == []

      @friendship = Friendship.new(user_id: @user.id, friend_id: params[:id])
    end

    if Friendship.where("user_id = ? AND friend_id = ?", params[:id], session[:user_id]) == []

      second_friendship = Friendship.new(user_id: params[:id], friend_id: @user.id )
    end

    if @friendship
      if @friendship.save
        if second_friendship

          if second_friendship.save
            flash[:success] = 'You have added new friend to your list.'
            redirect_to friendships_path
          end


        end
      end

    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def new
    @friendship = FriendList.new
  end

  def show
    @friends = User.where("id != (?)", @user.id)
  end

  def remove_friend
    friend1 = Friendship.where("user_id = ? AND friend_id = ?", session[:user_id], params[:id]).pluck(:id)
    friend2 = Friendship.where("user_id = ? AND friend_id = ?", params[:id], session[:user_id]).pluck(:id)

    Friendship.destroy(friend1)
    Friendship.destroy(friend2)
    flash[:success] = 'You have removed new friend to your list.'
    redirect_to friendships_path

  end

  def block_friend
    friendship = Friendship.where("user_id = ? AND friend_id = ?", session[:user_id], params[:id]).pluck(:id)
    if friendship
      @relationship = Friendship.find(friendship).first
      @relationship.update_attributes(status:'block')
      redirect_to friendships_path
    else
      newFriendBlock = Friendship.new(user_id: @user.id, friend_id: params[:id], status:'block')
      if newFriendBlock.save
        redirect_to friendships_path
      end
    end
  end

  private
  def check_friendship_status(user, friend)
    friendship = Friendship.find_by_user_id_and_friend_id(user, friend)
    byebug
    if friendship.status == 'block'
      'block'
    end
  end
  def set_user
    #@user ||= User.find(params[:user_id])

    @user ||= User.find(session[:user_id]) if session[:user_id]
    if @user == nil
      redirect_to '/'
    end
  end

  def get_list_friends(friendships)
    friends = []
    friendships.each do |f|
      friends << User.find(f.friend_id)
    end
    friends
  end

  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id, :status)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :set_user
  def index
    @messages = Message.where("recipient LIKE '%?%'", @user.id).order('created_at DESC')
  end

  def new
    @message = @user.messages.build
    @friends = @user.friends
  end

  def create
    @message = @user.messages.build(message_params)
    emailList = @message.recipient.split(',')
    recipientsList = User.where("email IN (?)", emailList).pluck(:id)*","
    @message.recipient = recipientsList
    if @message.save
      emailList.each do |e|
        ChatMailer.send_message_email(@message, User.find_by(email:e)).deliver_now
      end
      flash[:success] = 'You have sent a message.'
      redirect_to messages_path
    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def show_sent
    @messages = @user.messages.order('created_at DESC')
  end

  def show_message
    @message = Message.find(params[:id])
    if (@user.id != @message.user_id)
      ChatMailer.read_message_email(@message, @user).deliver_now
    end
    if !@message.is_read && @message.user_id != @user.id

      if @message.update_attributes(is_read:true, read_at:DateTime.now)

        flash[:message] = 'You have read the message'
      end
    end
    @recipients = User.find(@message.recipient.split(","))

  end

  private
  def set_user
    #@user ||= User.find(params[:user_id])

    @user ||= User.find(session[:user_id]) if session[:user_id]
    if @user == nil
      redirect_to '/'
    end
  end

  def message_params
    params.require(:message).permit(:content, :recipient)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email].strip)
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Login successfully'
      redirect_to messages_path
    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def callback
    if user = User.from_omniauth(env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to messages_path
    else
      # don't log user in
      redirect_to root_path
    end
  end

  def destroy
    flash[:success] = 'Logout successfully'
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session['user_id'] = @user.id
      redirect_to messages_path
    else
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(session['user_id'])

  end

  def update
    @user = User.find(session['user_id'])

    if @user.update_attributes(user_params)
      redirect_to users_edit_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :require_login
  def index
  end

  private
  def require_login
    if authorize_user?
      redirect_to messages_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {success: 'alert-success', error: 'alert-danger', warning: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "text-center alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'})
        concat message
      end)
      flash.clear
    end
    nil
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/_list.html.erb
<% count = 1 %>
<% @friends.each do |f| %>
    <% if count=1 %>
        <div class="grid">
    <% end %>
    <div class="grid-item col-md-3 text-xs-center">
      <% if f.avatar && f.avatar!='' %>
          <%= image_tag(f.avatar, class: "card-img-top", width: "150", height: "150") %>
      <% else %>
          <%= image_tag(asset_path("default_avatar.gif"), class: "card-img-top", width: "150", height: "150") %>
      <% end %>
      <div class="card-block">
        <h4 class="card-title"><%= f.name %></h4>
        <p class="card-text">
          <%= f.email %>
        </p>
        <% if (User.where("id NOT IN (?)", @user.friends.select(:id))).exists?(f.id) %>
            <%= link_to 'Make friends', friendships_create_path(id: f.id), class: "btn btn-success" %>
        <% else %>
            <%= link_to "Remove", remove_friend_path(id: f.id), class: "btn btn-warning" %>

        <% end %>

      </div>
    </div>
    <% if count==1 %>

        </div>
    <% else if count == 4%>
            <% count = 1 %>
        <% end %>
        <% count = count+1 %>
    <% end %>
<% end %>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/index.html.erb
<h1>Friends</h1>
<%= link_to 'All Users', 'friendships/show' %>

<%= render('list') %>

app/views/friendships/new.html.erb
<h1>Friendships#new</h1>
<p>Find me in app/views/friendships/new.html.erb</p>

app/views/friendships/show.html.erb
<h1>All Users</h1>

<%= render('list')  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeChat</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if authorize_user? %>
  <div class="top-nav">
    <h1>
      <%= image_tag(asset_path("Chat.png"), height: "50") %>
      Code Chat For Life
    </h1>
  </div>
  <div class="row wrapper">
    <div class="left-nav col-md-3">
      <div class="text-xs-center profile-field">
        <% if @user.avatar %>
            <%= image_tag(@user.avatar, height: "100", class: 'img-circle center-block') %>
            <% else %>
            <%= image_tag(asset_path("default_avatar.gif"), height: "100", class: 'img-circle center-block') %>
            <% end %>

        <a href="<%= users_edit_path %>"><h3><%= @user.name %></h3></a>
      </div>
    <div class="bootstrap-vertical-nav">

      <nav class="navbar navbar-light bg-faded">
        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
          &#9776;
        </button>
        <div class="collapse navbar-toggleable-sm" id="exCollapsingNavbar2">
          <ul class="nav navbar-nav">
            <li class="nav-item <%= current_page?(messages_path)? 'active': '' %>">
              <%= link_to 'Inbox', messages_path, class: 'nav-link'  %>

            </li>
            <li class="nav-item <%= current_page?(sent_path)? 'active': '' %>">
              <%= link_to 'Sent', sent_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= current_page?(friendships_path)? 'active': '' %>">
              <%= link_to 'Friends', friendships_path, class: 'nav-link' %>
            </li>

            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </nav>

    </div>
      <%= image_tag(asset_path("left_img.jpg"), width: "100%", class: 'center-block') %>
    </div>

    <div class="content col-md-9">
      <div><%= flash_messages  %></div>
      <%= yield %>
    </div>
    </div>

<% else %>
  <%= yield %>

<% end %>


</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
    <fieldset class="form-group">
      <label>Recipient</label>
      <ul id="emailFriendTags"></ul>
      <%= f.hidden_field 'recipient', id: "recipient", placeholder: "Recipients" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="content">Content</label>
      <%= f.text_area 'content', placeholder:"Enter your message here", class:"form-control", rows: '10' %>
    </fieldset>

  <%= f.submit 'Send', class:"btn btn-primary" %>
<% end %>

<script>
  $(function(){
    var sampleTags = <%= raw @friends.pluck(:email).to_json %>

    //-------------------------------
    // Single field
    //-------------------------------
    $('#emailFriendTags').tagit({
      availableTags: sampleTags,
      // This will make Tag-it submit a single form value, as a comma-delimited field.
      singleField: true,
      singleFieldNode: $('#recipient')
    });

  });
</script>

app/views/messages/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Content</th>
    <th>Sent at</th>
    <% if current_page?(sent_path) %>
        <th>Read at</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @messages.each do |m| %>
      <tr class="<%= (!m.is_read.present? && m.user.id != session[:user_id]) ? 'bold-text' : '' %>">
        <td><%= m.user.name %></td>
        <td><%= User.where(id: m.recipient.split(",")).pluck(:email).join(', ') %></td>
        <td>
          <% if (!m.is_read.present? && m.user.id != session[:user_id]) %>
          <a href="<%= show_message_path(id:m.id) %>"><%= truncate(m.content) %></a>
              <% else %>
              <%= truncate(m.content) %>
          <% end %>
        </td>
        <td><%= m.created_at %></td>
        <% if current_page?(sent_path) %>
            <td><%= m.read_at ? m.read_at : 'Not read' %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages</h1>

<%= render 'list' %>

<%= link_to "New Message", messages_new_path, class:"btn btn-primary" %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form' %>

app/views/messages/show_message.html.erb
<div class="message-show">
  <p><strong>From: </strong> <%= @message.user.name %> - <%= @message.user.email %></p>
  <p><strong>To: </strong>
      <% @recipients.each do |r| %>
          <span><%= r.email  %> </span>
      <% end %>
    </p>
  <p><strong>Date sent: </strong><%= @message.created_at %></p>
  <h5>Content</h5>
  <p>
    <%= @message.content %>
  </p>
</div>

app/views/messages/show_sent.html.erb
<h1>Sent Messages</h1>
<%= render 'list' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%= form_for(:user, url: users_update_path, method: :post) do |f| %>
    <fieldset class="form-group">
      <label for="name">Username </label>
      <%= f.text_field 'name', placeholder: 'Enter name here', class:'form-control'  %>
    </fieldset>
    <fieldset class="form-group">
      <label for="email">Email </label>
      <%= f.text_field 'email', placeholder: 'Enter email here', class:'form-control' %>
    </fieldset>
    <fieldset class="form-group">
      <label for="password">Password </label>
      <%= f.password_field 'password',  placeholder: 'Enter your password', class:'form-control'  %>

    </fieldset>
    <fieldset class="form-group">
      <label class="password_confirmation">Re enter your password </label>
      <%= f.password_field 'password_confirmation',  placeholder: 'Re-Enter your password', class:'form-control'  %>
    </fieldset>
    <fieldset class="form-group">

      <% if @user.avatar %>
          <%= image_tag(@user.avatar, height: "100", class: 'img-circle') %>
      <% else %>
          <%= image_tag(asset_path("default_avatar.gif"), height: "100", class: 'img-circle') %>
      <% end %>
      <%= f.file_field :avatar  %>

    </fieldset>



    <%= f.submit 'Update', class:'btn btn-success'  %>

<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="header-intro">
      <%= image_tag(asset_path("intro.jpg"), height: "320") %>
</div>

<div class="wrapper-intro">

  <div class="container" id="intro_part">
    <div class="col-md-6">

      <h1>
        <%= image_tag(asset_path("Chat.png"), height: "50") %>
        Code Chat For Life
      </h1>
    </div>
    <div class="col-md-6">
      <ul class="nav nav-tabs" role="tablist" id="welcome_form">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#login_form" role="tab">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#register_form" role="tab">Create an account</a>
        </li>

      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane active" id="login_form" role="tabpanel">

          <%= form_tag(login_path, method:'post') do %>
              <fieldset class="form-group">
                <label for="email">Email </label>
                <%= text_field_tag 'email', nil, placeholder:  'Enter email here', class:"form-control" %>
              </fieldset>
              <fieldset class="form-group">
                <label for="password">Password</label>
                <%= password_field_tag 'password', nil, placeholder: 'enter password here', class: 'form-control' %>
              </fieldset>
              <%= submit_tag 'Login', class:'btn btn-primary' %>

          <% end %>
        </div>
        <div class="tab-pane" id="register_form" role="tabpanel">
          <%= form_for(:user, url: register_path, method: :post) do |f| %>
              <fieldset class="form-group">
                <label for="name">Username </label>
                <%= f.text_field 'name', placeholder: 'Enter name here', class:'form-control'  %>
              </fieldset>
              <fieldset class="form-group">
                <label for="email">Email </label>
                <%= f.text_field 'email', placeholder: 'Enter email here', class:'form-control' %>
              </fieldset>
              <fieldset class="form-group">
                <label for="password">Password </label>
                <%= f.password_field 'password',  placeholder: 'Enter your password', class:'form-control'  %>

              </fieldset>
              <fieldset class="form-group">
                <label class="password_confirmation">Re enter your password </label>
                <%= f.password_field 'password_confirmation',  placeholder: 'Re-Enter your password', class:'form-control'  %>
              </fieldset>


              <%= f.submit 'Register', class:'btn btn-success'  %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  $(document).ready(function(){
    $('#welcome_form a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
  })
</script>